#   Copyright (c) 2006-2007 Open Source Applications Foundation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# Generated by the windmill services transformer
from windmill.authoring import WindmillTestClient

def test():
    client = WindmillTestClient(__name__)

    client.waits.forElement(xpath=u'html/body/center/p/font', timeout=u'3000')
    client.asserts.assertValue(validator=u'Google Search', name=u'btnG')
    client.asserts.assertValue(validator=u"I'm Feeling Lucky", name=u'btnI')
    client.asserts.assertImageLoaded(xpath=u'html/body/center/img')
    
    import windmill
    xmlrpc_client = windmill.tools.make_xmlrpc_client()
    xmlrpc_client.stop_runserver()
