# Generated by the windmill services transformer
from windmill.authoring import WindmillTestClient

def test_openid_authentication():
    client = WindmillTestClient(__name__)
    client.open(url='https://www.hampr.com/')
    client.waits.forPageLoad(timeout=20000)
    client.waits.forElement(xpath="//div[@id='hamprTitle']", timeout=8000)
    client.click(link='OpenID Login')
    client.waits.forPageLoad(timeout=20000)
    client.waits.forElement(xpath="//div[@id='pageContainer']/p[7]/b",
                            timeout=8000)
    client.click(xpath=u"//div[@id='pageContainer']/form/input")
    client.type(text='http://openid.claimid.com/windmilltest',
                xpath="//div[@id='pageContainer']/form/input")
    client.click(xpath="//div[@id='pageContainer']/form/input[2]")
    client.waits.forPageLoad(timeout=20000)
    client.waits.forElement(xpath="//div[@id='content']/form/fieldset/label",
                            timeout=28000)
    client.click(xpath="//div[@id='content']/form/fieldset/label")
    client.click(id='username')
    client.type(text='windmillTest', id='username')
    client.type(text='test_windmill', id='password')
    client.click(value='Login')
    client.waits.forPageLoad(timeout=20000)
