# Generated by the windmill services transformer
from windmill.authoring import WindmillTestClient

def test_google_switch_to_yahoo():
    client = WindmillTestClient(__name__)
    client.open(url=u'http://www.google.com/intl/en/')
    client.waits.forElement(timeout=u'', name=u'q')
    client.click(name=u'q')
    client.type(text=u'wikipedia', name=u'q')
    client.click(name=u'btnG')
    client.waits.forElement(link=u'Wikipedia', timeout=u'8000')
    client.click(link=u'Wikipedia')
    client.waits.forPageLoad(timeout=u'20000')
    client.asserts.assertJS(js=u"windmill.testWin().document.title == 'Wikipedia'")
    